
id: am-ui
version: 0.1.0
type: library
dependencies:
  - id: am-lang-core
    realm: github
    type: git-repo
    tag: latest
    url: https://github.com/anderskjeldsen/am-lang-core.git
platforms:
  - id: libc
    abstract: true
  - id: amigaos
    extends: libc
    gccCommand: m68k-amigaos-gcc -O3
    asmCommand: vasmm68k_mot
    additionalHeaders:
    additionalAsmSources:
    additionalCSources: 
    additionalIncludePaths:
    gccAdditionalOptions:
      - -noixemul     
    gccAdditionalLibraries:
      - socket
  - id: morphos-ppc
    extends: libc
    gccCommand: ppc-morphos-gcc -O3
    additionalHeaders:
    additionalAsmSources:
    additionalCSources: 
    additionalIncludePaths:
    gccAdditionalOptions:
      - -noixemul     
    gccAdditionalLibraries:

buildTargets:
  - id: amigaos_docker_arm64
    platform: amigaos
    dockerBuild:
      image: kjeldsenanders/dnf-dev:initial
      buildPath: /host
  - id: amigaos_docker_x64
    platform: amigaos
    dockerBuild:
      image: kjeldsenanders/dnf-dev:initial-x86
      buildPath: /host
  - id: morphos-ppc_docker
    platform: morphos-ppc
    dockerBuild:
      image: amigadev/crosstools:ppc-morphos
      buildPath: /work

