
id: am-ui
version: 0.1.0
type: library
dependencies:
  - id: am-lang-core
#    realm: github
#    type: git-repo
#    tag: latest
#    url: https://github.com/anderskjeldsen/am-lang-core.git
    type: local
    path: ../am-lang-core
  - id: am-imaging
    realm: github
    type: git-repo
    tag: latest
    url: https://github.com/anderskjeldsen/am-imaging.git

platforms:
  - id: libc
    abstract: true
  - id: amigaos
    extends: libc
    gccCommand: m68k-amigaos-gcc -O3
    asmCommand: vasmm68k_mot
    additionalHeaders:
    additionalAsmSources:
    additionalCSources: 
    additionalIncludePaths:
    gccAdditionalOptions:
      - -noixemul     
      - -UHAVE_TIMEGM
    gccAdditionalLibraries:
#      - socket
  - id: morphos-ppc
    extends: libc
    gccCommand: ppc-morphos-gcc -O3
    additionalHeaders:
    additionalAsmSources:
    additionalCSources: 
    additionalIncludePaths:
    gccAdditionalOptions:
      - -noixemul     
    gccAdditionalLibraries:

buildTargets:
  - id: amigaos_docker
    platform: amigaos
    dockerBuild:
      image: amiga-gcc:latest
      buildPath: /host
  - id: morphos-ppc_docker
    platform: morphos-ppc
    dockerBuild:
      image: amigadev/crosstools:ppc-morphos
      buildPath: /work

