
id: am-ui
version: 0.1.0
type: library
dependencies:
  - id: am-lang-core
    realm: github
    type: git-repo
    tag: latest
    url: https://github.com/anderskjeldsen/am-lang-core.git
platforms:
  - id: libc
    abstract: true
  - id: amigaos
    extends: libc
    gccCommand: m68k-amigaos-gcc
    asmCommand: vasmm68k_mot
    additionalHeaders:
    additionalAsmSources:
    additionalCSources: 
    additionalIncludePaths:
#      - c-libs/libpng15/include
#      - c-libs/zlib/nofpu/include
    gccAdditionalOptions:
      - -noixemul     
#      - -lm
buildTargets:
  - id: amigaos_docker_win_anders
    platform: amigaos
    commands:
      - docker run -v ${build_dir}:/host -i d931759c3883 make -f amigaos.makefile -C /host all
  - id: amigaos_docker_matebook_anders
    platform: amigaos
    commands:
      - docker run -v ${build_dir}:/host kjeldsenanders/dnf-dev:initial-x86 make -f amigaos.makefile -C /host ${make_target}
  - id: amigaos_docker_macm1_anders
    platform: amigaos
    commands:
      - docker run -v ${build_dir}:/host kjeldsenanders/dnf-dev:initial make -f amigaos.makefile -C /host all
  - id: macos
    platform: amigaos
    commands:
      - make -f linux-x64.makefile