#pragma once
#include <libc/core.h>
#include <Am/Ui/Bitmap.h>
#include <Am/Lang/ClassRef.h>
#include <Am/Lang/Object.h>
#include <Am/Lang/UShort.h>
#include <Am/Ui/BitmapPixelFormat.h>
#include <Am/Ui/Window.h>
#include <Am/Imaging/Image.h>
