#pragma once
#include <libc/core.h>
#include <Am/Ui/Font.h>
#include <Am/Lang/ClassRef.h>
#include <Am/Lang/String.h>
#include <Am/Lang/Object.h>
#include <Am/Lang/UByte.h>
#include <Am/Lang/UShort.h>
#include <Am/Collections/HashMap.h>
#include <Am/Lang/Bool.h>
