#pragma once
#include <libc/core.h>
#include <Mesh3D/Renderer3D.h>
#include <Am/Lang/ClassRef.h>
#include <Am/Lang/UInt.h>
#include <Am/Lang/Array.h>
#include <Am/Lang/Double.h>
#include <Am/Lang/Int.h>
#include <Am/Graphics3D/Mesh.h>
#include <Am/Imaging/Image.h>
#include <Am/Lang/Object.h>
#include <Am/Graphics3D/Matrix3.h>
#include <Am/Util/Math.h>
#include <Am/Graphics3D/Polygon.h>
#include <Am/Lang/UShort.h>
#include <Am/Graphics3D/Vector3.h>
#include <Am/Lang/Bool.h>
#include <Am/Lang/Short.h>
